version: '2.1'
services:

  mender-redis:
    restart: unless-stopped
    image: redis:${DOCKER_REDIS:-3.2.11-alpine}
    ports:
      - '${PORT_REDIS:-6379}:6379'
    volumes:
      - redis:/var/lib/redis:rw
      - ./conductor/redis/redis.conf:/etc/redis/redis.conf:ro
      - ./conductor/redis/entrypoint.sh:/redis/entrypoint.sh:ro
    entrypoint: /redis/entrypoint.sh

  mender-conductor:
    restart: unless-stopped
    environment:
      - 'CONFIG_PROP=config.properties'
    image: mendersoftware/mender-conductor:${DOCKER_MENDER_CONDUCTOR:-1.2.0}
    volumes:
      - ./conductor/server/config:/app/config:ro
    links:
      - 'elasticsearch'
      - 'mender-redis'

  minio:
    restart: unless-stopped
    environment:
      - 'MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-mender-deployments}'
      - 'MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minio-secret-change-me}'
    image: minio/minio:${DOCKER_MINIO:-RELEASE.2018-09-25T21-34-43Z}
    volumes:
      - mender-artifacts:/export:rw
    command: server /export

  storage-proxy:
    restart: unless-stopped
    image: openresty/openresty:${DOCKER_OPENRESTY:-1.13.6.2-0-alpine}
    links:
      - minio
    ports:
      - "${PORT_MINIO:-9000}:9000"
    environment:
      - 'DOWNLOAD_SPEED=5m'
      - 'MAX_CONNECTIONS=50'
    volumes:
      - ./storage-proxy/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./fullchain.pem:/var/www/storage-proxy/cert/cert.crt:ro
      - ./server.key:/var/www/storage-proxy/cert/private.key:ro

  mender-deployments:
    restart: unless-stopped
    environment:
      - 'DEPLOYMENTS_MONGO_USERNAME=bluerange'
      - 'DEPLOYMENTS_MONGO_PASSWORD=${MONGO_PASSWORD:-bluerange-mongodb-pwd-change-me}'
      # SSL certs
      - 'STORAGE_BACKEND_CERT=/etc/ssl/certs/storage-proxy.crt'
      # access key, the same value as MINIO_ACCESS_KEY
      - 'DEPLOYMENTS_AWS_AUTH_KEY=${MINIO_ACCESS_KEY:-mender-deployments}'
      # secret, the same valie as MINIO_SECRET_KEY
      - 'DEPLOYMENTS_AWS_AUTH_SECRET=${MINIO_SECRET_KEY:-minio-secret-change-me}'
      # deployments service uses signed URLs, hence it needs to access
      # storage-proxy using exactly the same name as devices will; if
      # devices will access storage using https://s3.acme.org:9000, then
      # set this to https://s3.acme.org:9000
      - 'DEPLOYMENTS_AWS_URI=https://${HOST}:${PORT_MINIO:-9000}'
    image: mendersoftware/deployments:${DOCKER_MENDER_DEPLOYMENTS:-1.6.0}
    links:
      - 'mongodb:mongo-deployments'
      - 'storage-proxy:${HOST}'
    command: server
    volumes:
      - ./ca.pem:/etc/ssl/certs/storage-proxy.crt:ro

  mender-gui:
    restart: unless-stopped
    environment:
      - 'INTEGRATION_VERSION'
    image: mendersoftware/gui:${DOCKER_MENDER_GUI:-1.7.0}

  mender-api-gateway:
    restart: unless-stopped
    environment:
      - 'BLUERANGE_COMPOSE_SH=${BLUERANGE_COMPOSE_SH:?>>> Use ./bluerange-compose.sh instead of docker-compose! <<<}'
      - 'ALLOWED_HOSTS=${HOST}:${PORT_MENDER:-444}'
    image: mendersoftware/api-gateway:${DOCKER_MENDER_API_GATEWAY:-1.6.0}
    links:
      - mender-device-auth
      - mender-deployments
      - mender-gui
      - mender-useradm
      - mender-inventory
    ports:
      - '${PORT_MENDER:-444}:443'
    volumes:
      - ./fullchain.pem:/var/www/mendersoftware/cert/cert.crt:ro
      - ./server.key:/var/www/mendersoftware/cert/private.key:ro
      - ./entrypoint-no-http2.sh:/entrypoint-no-http2.sh
    entrypoint: ["/entrypoint-no-http2.sh"]

  mender-device-auth:
    restart: unless-stopped
    environment:
      - 'DEVICEAUTH_MONGO_USERNAME=bluerange'
      - 'DEVICEAUTH_MONGO_PASSWORD=${MONGO_PASSWORD:-bluerange-mongodb-pwd-change-me}'
    image: mendersoftware/deviceauth:${DOCKER_MENDER_DEVICEAUTH:-1.7.0}
    links:
      - 'mongodb:mongo-device-auth'
    command: server --automigrate
    volumes:
      - ./server.rsa:/etc/deviceauth/rsa/private.pem:ro

  mender-inventory:
    restart: unless-stopped
    environment:
      - 'INVENTORY_MONGO_USERNAME=bluerange'
      - 'INVENTORY_MONGO_PASSWORD=${MONGO_PASSWORD:-bluerange-mongodb-pwd-change-me}'
    image: mendersoftware/inventory:${DOCKER_MENDER_INVENTORY:-1.5.0}
    links:
      - 'mongodb:mongo-inventory'
    command: server --automigrate

  mender-useradm:
    restart: unless-stopped
    environment:
      - 'USERADM_MONGO_USERNAME=bluerange'
      - 'USERADM_MONGO_PASSWORD=${MONGO_PASSWORD:-bluerange-mongodb-pwd-change-me}'
    image: mendersoftware/useradm:${DOCKER_MENDER_USERADM:-1.7.0}
    links:
      - 'mongodb:mongo-useradm'
    command: server --automigrate
    volumes:
      - ./server.rsa:/etc/useradm/rsa/private.pem:ro

volumes:
  redis:
  mender-artifacts:
