version: '2.1'
services:

  bluerange:
    env_file:
      - './server.env'
    environment:
      - 'HOSTNAME=https://$${HOST}'
      - 'TZ=UTC'
      - 'DATABASE_TYPE=mariadb'
      - 'DATABASE_URL=jdbc:mariadb://database/bluerange?useServerPrepStmts=true'
      - 'DATABASE_USER=bluerange'
      - 'DATABASE_PWD=bluerange-database-pwd-change-me'
      - 'RELUTION_MONGODB_ENABLED=true'
      - 'MONGO_DATABASE=bluerange'
      - 'MONGO_HOST=mongodb'
      - 'MONGO_PORT=27017'
      - 'MONGO_USERNAME=bluerange'
      - 'MONGO_PASSWORD=bluerange-mongodb-pwd-change-me'
      - 'MONGO_AUTHENTICATION_DATABASE=admin'
      - 'MQTT_ENABLED=true'
      - 'MQTT_SERVER_URIS=ssl://$${HOST}:8884,wss://$${HOST}:9002'
      - 'ORGA_NAME=iot'
      - 'ORGA_FULLNAME=IOT'
      - 'ORGA_ADMIN_USERNAME=admin'
      - 'ORGA_ADMIN_GIVENNAME=IOT'
      - 'ORGA_ADMIN_SURNAME=Administrator'
      - 'ORGA_ADMIN_PASSWORD=iot12345'
    depends_on:
      database:
        condition: service_healthy
    ports:
      - '8081:8080'
      - '8100:8099'
    expose:
      - '7800'
      - '8080'
      - '8099'
    image: bluerange/bluerange:latest
    links:
      - 'database'
      - 'mongodb'

  database:
    environment:
      - 'MYSQL_PASSWORD=bluerange-database-pwd-change-me'
      - 'MYSQL_USER=bluerange'
      - 'MYSQL_DATABASE=bluerange'
      - 'MYSQL_ROOT_PASSWORD=root-database-pwd-change-me'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '3307:3306'
    expose:
      - '3306'
    # MariaDB 10.4.9 and 10.4.10 is currently not supported. Please use MariaDB 10.4.8.
    #image: mariadb:latest
    image: mariadb:10.4.8
    volumes:
      - './initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro'
      - './database.cnf:/etc/mysql/conf.d/database.cnf:ro'
      - 'mysql:/var/lib/mysql:rw'

  mongodb:
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=bluerange'
      - 'MONGO_INITDB_ROOT_PASSWORD=bluerange-mongodb-pwd-change-me'
      - 'MONGO_INITDB_DATABASE=bluerange'
    ports:
      - '27018:27017'
    expose:
      - '27017'
    image: mongo:latest
    volumes:
      - 'mongodb:/data/db:rw'

  nginx:
    ports:
      - '443:443'
    expose:
      - '80'
      - '443'
    image: nginx:latest
    #command: /bin/bash -c "nginx-debug -g 'daemon off;'"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './mime.types:/etc/nginx/mime.types:ro'
      - './server.key:/etc/nginx/server.key:ro'
      - './server.pem:/etc/nginx/server.pem:ro'
      - './htpasswd:/etc/nginx/htpasswd:ro'
    links: 
      - 'bluerange'
      - 'mosquitto'
      - 'nodered'

  mosquitto:
    restart: always
    ports:
      - '1884:1883'
      - '8884:8883'
      - '9002:9001'
    expose:
      - '1883'
      - '8883'
      - '9001'
    image: relution/relution-mosquitto:latest
    volumes:
      #- './mosquitto.conf:/etc/mosquitto/mosquitto.conf:ro'
      - './server.key:/etc/mosquitto/server.key:ro'
      - './server.pem:/etc/mosquitto/server.pem:ro'
    links:
      # relution-mosquitto image assumes relution as authentication server
      - 'bluerange:relution'

  nodered:
    ports:
      - '1881:1880'
    expose:
      - '1880'
    image: nodered/node-red-docker:latest
    volumes:
      - 'nodered:/data:rw'
    links:
      - 'bluerange'
      - 'mosquitto'
      - 'database'
      - 'mongodb'

volumes:
  mysql:
  mongodb:
  nodered:
