version: '3.9'
services:

  elasticsearch:
    command: /scripts/setElasticSearchPermsAndStartEntryPoint.sh
    restart: unless-stopped
    environment:
      - 'BLUERANGE_COMPOSE_SH=${BLUERANGE_COMPOSE_SH:?>>> Use ./bluerange-compose.sh instead of docker-compose! <<<}'
      - 'cluster.name=bluerange'
      - 'discovery.type=single-node'
    labels:
      - 'LOGSENE_ENABLED=false'
    ports:
      - '${PORT_ELASTICSEARCH:-9200}:9200'
      - '${PORT_ELASTICSEARCH_9600:-127.0.0.1:9600}:9600'
    expose:
      - '9200'
      - '9600'
    image: amazon/opendistro-for-elasticsearch:${DOCKER_ELASTICSEARCH:-1.1.0}
    volumes:
      - './configs/scripts/setElasticSearchPermsAndStartEntryPoint.sh:/scripts/setElasticSearchPermsAndStartEntryPoint.sh:ro'
      - './configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - './certs/fullchain.pem:/usr/share/elasticsearch/config/server.pem.copy:ro'
      - './certs/server.key:/usr/share/elasticsearch/config/server.key.copy:ro'
      - 'elasticsearch:/usr/share/elasticsearch/data:rw'
    logging:
      driver: 'json-file'
      options:
        max-size: '${DOCKER_ELASTICSEARCH_LOGSIZE:-32m}'
        max-file: '4'
        compress: 'true'

  kibana:
    restart: unless-stopped
    environment:
      # see https://aws.amazon.com/de/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/
      # see https://www.elastic.co/guide/en/kibana/5.0/_configuring_kibana_on_docker.html
      - 'SERVER_NAME=${HOST}'
      - 'SERVER_SSL_ENABLED=true'
      - 'SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/server.pem'
      - 'SERVER_SSL_KEY=/usr/share/kibana/config/server.key'
      - 'ELASTICSEARCH_URL=https://elasticsearch:9200'
      - 'ELASTICSEARCH_HOSTS=https://elasticsearch:9200'
    labels:
      - 'LOGSENE_ENABLED=false'
    ports:
      - '${PORT_KIBANA:-5601}:5601'
    expose:
      - '5601'
    image: amazon/opendistro-for-elasticsearch-kibana:${DOCKER_KIBANA:-1.1.0}
    volumes:
      - './certs/fullchain.pem:/usr/share/kibana/config/server.pem:ro'
      - './certs/server.key:/usr/share/kibana/config/server.key:ro'
    links:
      - 'elasticsearch'
    logging:
      driver: 'json-file'
      options:
        max-size: '${DOCKER_KIBANA_LOGSIZE:-16m}'
        max-file: '4'
        compress: 'true'

  logagent:
    restart: unless-stopped
    environment:
      - 'LOGS_RECEIVER_URL=https://admin:admin@elasticsearch:9200'
      - 'LOGS_TOKEN=bluerange'
      - 'NODE_TLS_REJECT_UNAUTHORIZED=0'
    labels:
      - 'LOGSENE_ENABLED=false'
    cap_add:
      - SYS_ADMIN
    image: sematext/logagent:${DOCKER_LOGAGENT:-3.0.2}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    links:
      - 'elasticsearch'
    logging:
      driver: 'json-file'
      options:
        max-size: '${DOCKER_LOGAGENT_LOGSIZE:-8m}'
        max-file: '4'
        compress: 'true'

volumes:
  elasticsearch:
