version: '2.1'
services:

  elasticsearch:
    environment:
      - 'BLUERANGE_COMPOSE_SH=${BLUERANGE_COMPOSE_SH:?>>> Use ./bluerange-compose.sh instead of docker-compose! <<<}'
      - 'cluster.name=bluerange'
      - 'discovery.type=single-node'
    labels:
      - 'LOGSENE_ENABLED=false'
    ports:
      - '9201:9200'
      - '9601:9600'
    expose:
      - '9200'
      - '9600'
    image: amazon/opendistro-for-elasticsearch:${DOCKER_ELASTICSEARCH:-1.1.0}
    volumes:
      - './elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - './fullchain.pem:/usr/share/elasticsearch/config/server.pem:ro'
      - './server.key:/usr/share/elasticsearch/config/server.key:ro'
      - 'elasticsearch:/usr/share/elasticsearch/data:rw'

  kibana:
    environment:
      # see https://aws.amazon.com/de/blogs/opensource/add-ssl-certificates-open-distro-for-elasticsearch/
      # see https://www.elastic.co/guide/en/kibana/5.0/_configuring_kibana_on_docker.html
      - 'SERVER_NAME=${HOST}'
      - 'SERVER_SSL_ENABLED=true'
      - 'SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/server.pem'
      - 'SERVER_SSL_KEY=/usr/share/kibana/config/server.key'
      - 'ELASTICSEARCH_URL=https://elasticsearch:9200'
      - 'ELASTICSEARCH_HOSTS=https://elasticsearch:9200'
    labels:
      - 'LOGSENE_ENABLED=false'
    ports:
      - '5602:5601'
    expose:
      - '5601'
    image: amazon/opendistro-for-elasticsearch-kibana:${DOCKER_KIBANA:-1.1.0}
    volumes:
      - './fullchain.pem:/usr/share/kibana/config/server.pem:ro'
      - './server.key:/usr/share/kibana/config/server.key:ro'
    links:
      - 'elasticsearch'

  logagent:
    environment:
      - 'LOGS_RECEIVER_URL=https://admin:admin@elasticsearch:9200'
      - 'LOGS_TOKEN=bluerange'
      - 'NODE_TLS_REJECT_UNAUTHORIZED=0'
    labels:
      - 'LOGSENE_ENABLED=false'
    cap_add:
      - SYS_ADMIN
    image: sematext/logagent:${DOCKER_LOGAGENT:-3.0.2}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    links:
      - 'elasticsearch'

volumes:
  elasticsearch:
