{
 "title": "BlueRange Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"bluerange-io\"}"
    }
   ]
  },
  {
   "title": "Position Estimate Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iot_position_estimate_load_count{}[5m])"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_cpu_usage{}" }
   ]
  },
  {
   "title": "Sensor Data Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iot_sensor_data_load_count{}[5m])"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{}[5m])"
    }
   ]
  },
  {
   "title": "Calibration Measurement Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iot_calibration_measurement_load_count{}[5m])"
    }
   ]
  },
  {
   "title": "MQTT Message Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(counter_mqtt_messages_incoming_total{}[5m])",
     "legendFormat": "Incoming ({{instance}})"
    },
    {
     "expr": "rate(counter_mqtt_messages_outgoing_total{}[5m])",
     "legendFormat": "Outgoing ({{instance}})"
    }
   ]
  }
 ]
}