{
 "title": "Gateway Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "gateway", "query": "meshgw.*" }
  ]
 },
 "panels": [
  {
   "title": "($gateway) Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "gateway",
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "target": "meshgw.$gateway.process_uptime" }
   ]
  },
  {
   "title": "($gateway) Start Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "repeat": "gateway",
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "target": "meshgw.$gateway.process_start_time"
    }
   ]
  },
  {
   "title": "($gateway) MQTT Total Message Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "gateway",
   "targets": [
    {
     "target": "alias(meshgw.$gateway.counter_mqtt_messages_incoming.count, 'incoming')"
    },
    {
     "target": "alias(meshgw.$gateway.counter_mqtt_messages_outgoing.count, 'outgoing')"
    }
   ]
  },
  {
   "title": "($gateway) MQTT Client",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "gateway",
   "targets": [
    {
     "target": "alias(meshgw.$gateway.counter_mqtt_connect_success.count, 'connect success')"
    },
    {
     "target": "alias(meshgw.$gateway.counter_mqtt_connect_failures.count, 'connect failures')"
    },
    {
     "target": "alias(meshgw.$gateway.counter_mqtt_reconnects.count, 'reconnect')"
    }
   ]
  },
  {
   "title": "($gateway) MQTT Messages (average) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_mqtt_messages_incoming.m1_rate, 60), ' Incoming /s ')"
    },
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_mqtt_messages_outgoing.m1_rate, 60), ' Outgoing /s ')"
    }
   ]
  },
  {
   "title": "($gateway) IP Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_network_ipnet_bytes_received.m1_rate, 60), 'Bytes Received')"
    },
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_network_ipnet_bytes_transferred.m1_rate, 60), 'Bytes Sent')"
    }
   ]
  },
  {
   "title": "($gateway) Mesh Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_network_mesh_bytes_received.m1_rate, 60), ' Bytes Received')"
    },
    {
     "target": "alias(scaleToSeconds(meshgw.$gateway.counter_network_mesh_bytes_transferred.m1_rate, 60), 'Bytes Sent')"
    }
   ]
  },
  {
   "title": "($gateway) JVM CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(meshgw.$gateway.system_cpu_load, ' ')"
    }
   ]
  },
  {
   "title": "($gateway) OS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(meshgw.$gateway.system_memory_used, ' ')"
    }
   ]
  }
 ]
}