{
 "title": "Mqtt Internals",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Message queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_waiting_messages{}", "legendFormat": "Waiting messages" },
    { "expr": "mqtt_retained_messages{}", "legendFormat": "Retained messages" },
    { "expr": "mqtt_stored_messages{}", "legendFormat": "Stored messages" }
   ]
  },
  {
   "title": "Message traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_received_messages{}", "legendFormat": "Received messages" },
    { "expr": "mqtt_sent_messages{}", "legendFormat": "Sent messages" }
   ]
  },
  {
   "title": "Byte traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mqtt_received_bytes{}", "legendFormat": "Received bytes" },
    { "expr": "mqtt_sent_bytes{}", "legendFormat": "Sent bytes" }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_active_subscriptions{}", "legendFormat": "Active subscriptions" }
   ]
  },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mqtt_connected_clients{}", "legendFormat": "Connected clients" },
    { "expr": "auth_logins_user_count{}", "legendFormat": "Authorized clients" }
   ]
  },
  {
   "title": "Attack prevention",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "auth_duplicatelist_length{}", "legendFormat": "Duplicatelist" },
    { "expr": "auth_blacklist_length{}", "legendFormat": "Blacklist" }
   ]
  },
  {
   "title": "Authentication requests",
   "type": "graph",
   "description": "Number of authentication requests against BlueRange server",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(auth_server_request_count{}[5m])",
     "legendFormat": "Authentication requests per 5m"
    }
   ]
  },
  {
   "title": "Authentication response",
   "type": "graph",
   "description": "A running average of the request/response round-trip time when authenticating with the BlueRange server via REST",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "auth_server_request_time{}", "legendFormat": "Response time running average" }
   ]
  }
 ]
}