{
 "title": "Mqtt Realtime Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Open connection to broker",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mqtt_open_connection_seconds{}" }
   ]
  },
  {
   "title": "Send message duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_message_delivery_seconds{}"
    }
   ]
  },
  {
   "title": "Average byte per message per organisation",
   "type": "bargauge",
   "description": "Shows the average of the published messages per organisation over the last minute",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_organisation_published_average_bytes_per_message{site='ALL'}",
     "legendFormat": "{{organisation_name}}"
    }
   ]
  },
  {
   "title": "Published messages per organisation",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_organisation_published_messages{site='ALL'}",
     "legendFormat": "{{organisation_name}}"
    }
   ]
  },
  {
   "title": "Connected clients",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_connected_clients{}" }
   ]
  },
  {
   "title": "Active subscriptions",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mqtt_active_subscriptions{}" }
   ]
  }
 ]
}