{
 "title": "Mqtt Organisation",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Messages Per Site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_organisation_published_messages{topic=\"ALL\"}",
     "legendFormat": "{{site}}"
    }
   ]
  },
  {
   "title": "Average bytes per published message per organisation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mqtt_organisation_published_average_bytes_per_message{site=\"ALL\", topic=\"ALL\"}",
     "legendFormat": "{{organisation_name}}"
    }
   ]
  },
  {
   "title": "Published messages per organisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mqtt_organisation_published_messages{site=\"ALL\"}",
     "legendFormat": "{{organisation_name}}"
    }
   ]
  },
  {
   "title": "Published bytes per organisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mqtt_organisation_published_bytes{site=\"ALL\"}",
     "legendFormat": "{{organisation_name}}"
    }
   ]
  }
 ]
}