apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:8080
    jsonData:
       graphiteVersion: "1.1.x"
    basicAuth: false
    editable: true
